package com.arthur.nettools.ui.screens

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Apps
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Error
import androidx.compose.material.icons.filled.Https
import androidx.compose.material.icons.filled.Key
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Stop
import androidx.compose.material.icons.filled.UnfoldMore
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ElevatedCard
import androidx.compose.material3.FilledTonalButton
import androidx.compose.material3.Icon
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedCard
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.arthur.nettools.MainViewModel
import com.arthur.nettools.capture.AppTarget
import com.arthur.nettools.intercept.AddonStatus
import com.arthur.nettools.intercept.DecryptedKind
import com.arthur.nettools.intercept.InterceptionOptions
import com.arthur.nettools.intercept.InterceptionPhase
import com.arthur.nettools.intercept.InterceptionState
import com.arthur.nettools.intercept.InterceptionSession
import com.arthur.nettools.security.CaStatus
import java.text.DateFormat
import java.util.Date

@Composable
fun DecryptScreen(
    state: InterceptionState,
    addon: AddonStatus,
    ca: CaStatus,
    apps: List<AppTarget>,
    history: List<InterceptionSession>,
    viewModel: MainViewModel,
    onCertificate: () -> Unit,
    onEvent: (Long) -> Unit,
    onHistorySession: (String) -> Unit,
) {
    var selected by remember { mutableStateOf<AppTarget?>(null) }
    var picker by remember { mutableStateOf(false) }
    var blockQuic by remember { mutableStateOf(true) }
    var restartTarget by remember { mutableStateOf(true) }
    var fullPayload by remember { mutableStateOf(true) }
    var confirmReboot by remember { mutableStateOf(false) }
    val active = state.phase == InterceptionPhase.RUNNING || state.phase == InterceptionPhase.STARTING || state.phase == InterceptionPhase.STOPPING
    val caMatchesMitm = ca.source?.contains("mitm", true) == true
    val ready = state.rootAvailable && addon.installed && caMatchesMitm && ca.systemTrusted

    LazyColumn(contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
        item {
            ElevatedCard(Modifier.fillMaxWidth()) {
                Column(Modifier.padding(18.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    Text("Decryption readiness", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.SemiBold)
                    SetupRow("Root access", state.rootAvailable, if (state.rootAvailable) "Transparent redirection available" else "Grant Magisk root")
                    SetupRow("MITM add-on", addon.installed, addon.versionName?.let { "Version $it" } ?: "Install mitmproxy runtime")
                    SetupRow("Interception CA", caMatchesMitm, ca.source ?: "Import the CA generated by the add-on")
                    SetupRow("System trust", ca.systemTrusted, when {
                        ca.systemTrusted -> "CA is active in Android system trust"
                        ca.systemModuleInstalled -> "Magisk module staged; reboot required"
                        else -> "Install the interception CA as a system CA"
                    })
                    if (addon.busy) {
                        LinearProgressIndicator(Modifier.fillMaxWidth())
                        Text(addon.message ?: "Working…", style = MaterialTheme.typography.bodySmall)
                    }
                    if (!addon.installed) Button(onClick = viewModel::installMitmAddon, modifier = Modifier.fillMaxWidth()) { Text("Install official MITM add-on") }
                    if (addon.installed && !caMatchesMitm) Button(onClick = viewModel::importMitmCa, modifier = Modifier.fillMaxWidth()) { Text("Import add-on CA") }
                    if (caMatchesMitm && !ca.systemModuleInstalled) Button(onClick = viewModel::installCa, modifier = Modifier.fillMaxWidth()) { Text("Install CA into system trust") }
                    if (ca.requiresReboot) Button(onClick = { confirmReboot = true }, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.Refresh, null); Spacer(Modifier.padding(4.dp)); Text("Reboot to activate CA") }
                    OutlinedButton(onClick = onCertificate, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.Key, null); Spacer(Modifier.padding(4.dp)); Text("Certificate details") }
                }
            }
        }

        if (state.lastError != null) item {
            ElevatedCard(Modifier.fillMaxWidth()) {
                Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.Error, null); Spacer(Modifier.padding(5.dp))
                    Column { Text("Interception error", fontWeight = FontWeight.SemiBold); Text(state.lastError, color = MaterialTheme.colorScheme.onSurfaceVariant) }
                }
            }
        }

        item {
            Text("Target application", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
            Spacer(Modifier.height(6.dp))
            OutlinedCard(Modifier.fillMaxWidth().clickable(enabled = !active) { picker = true }) {
                Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.Apps, null); Spacer(Modifier.padding(6.dp))
                    Column(Modifier.weight(1f)) {
                        val target = state.target ?: selected
                        Text(target?.label ?: "Choose an app", fontWeight = FontWeight.Medium)
                        Text(target?.packageName ?: "TLS interception is deliberately per-app", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                    Icon(Icons.Default.UnfoldMore, null)
                }
            }
        }

        item {
            ElevatedCard(Modifier.fillMaxWidth()) {
                Column(Modifier.padding(18.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text("Compatibility profile", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
                    SettingSwitch("Force QUIC → TCP fallback", "Blocks UDP/443 only for the selected UID so HTTP/3 can fall back to TLS over TCP.", blockQuic, !active) { blockQuic = it }
                    SettingSwitch("Restart target app", "Closes existing sockets after interception starts so new TLS handshakes use the interception CA.", restartTarget, !active) { restartTarget = it }
                    SettingSwitch("Store full payload", "Keeps complete decrypted bodies on-device, which may include credentials or private content. UI previews redact common auth headers. Disable to reduce sensitive data and disk usage.", fullPayload, !active) { fullPayload = it }
                }
            }
        }

        item {
            val target = selected
            Button(
                onClick = {
                    if (active) viewModel.stopInterception()
                    else if (target != null) viewModel.startInterception(target, InterceptionOptions(blockQuic, restartTarget, fullPayload))
                },
                enabled = if (active) true else ready && target != null,
                modifier = Modifier.fillMaxWidth().height(56.dp), shape = RoundedCornerShape(18.dp),
            ) {
                Icon(if (active) Icons.Default.Stop else Icons.Default.Https, null); Spacer(Modifier.padding(4.dp))
                Text(if (active) "Stop decryption" else "Start TLS decryption")
            }
            if (!ready && !active) Text("Complete the readiness steps above before interception can start.", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, modifier = Modifier.padding(top = 6.dp))
        }

        if (state.session != null) item {
            ElevatedCard(Modifier.fillMaxWidth()) {
                Column(Modifier.padding(18.dp), verticalArrangement = Arrangement.spacedBy(5.dp)) {
                    Text(if (state.phase == InterceptionPhase.RUNNING) "Live session" else "Latest decrypted session", fontWeight = FontWeight.SemiBold)
                    Text(state.session.target.label)
                    Text("${state.session.decryptedEvents} events · ${state.session.httpRequests} HTTP requests · ${state.session.tlsErrors} TLS errors")
                    Text(state.session.directory, style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant, maxLines = 2, overflow = TextOverflow.Ellipsis)
                    if (state.phase == InterceptionPhase.STARTING) LinearProgressIndicator(Modifier.fillMaxWidth())
                }
            }
        }

        if (state.httpExchanges.isNotEmpty()) {
            item { Text("HTTP requests", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold) }
            items(state.httpExchanges.take(30), key = { "http-${it.id}" }) { http ->
                OutlinedCard(Modifier.fillMaxWidth()) {
                    Column(Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(3.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(http.method ?: "HTTP", fontWeight = FontWeight.Bold)
                            Spacer(Modifier.weight(1f))
                            http.statusCode?.let { Text(it.toString(), color = if (it < 400) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error) }
                        }
                        Text(http.host ?: http.requestLine ?: http.responseLine ?: "Port ${http.port}", maxLines = 1, overflow = TextOverflow.Ellipsis)
                        Text(http.requestLine ?: http.responseLine.orEmpty(), style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, maxLines = 2, overflow = TextOverflow.Ellipsis)
                        Text("${http.requestBytes} B → ${http.responseBytes} B${http.contentType?.let { " · $it" } ?: ""}", style = MaterialTheme.typography.labelSmall)
                    }
                }
            }
        }

        if (state.recentEvents.isNotEmpty()) {
            item { Text("Decrypted events", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold) }
            items(state.recentEvents.take(60), key = { "event-${it.id}" }) { event ->
                OutlinedCard(Modifier.fillMaxWidth().clickable { onEvent(event.id) }) {
                    Column(Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(3.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(if (event.kind == DecryptedKind.TLS_ERROR) Icons.Default.Error else Icons.Default.CheckCircle, null)
                            Spacer(Modifier.padding(4.dp)); Text(event.title, fontWeight = FontWeight.SemiBold); Spacer(Modifier.weight(1f)); Text("${event.size} B", style = MaterialTheme.typography.labelSmall)
                        }
                        Text(event.preview, maxLines = 3, overflow = TextOverflow.Ellipsis, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                }
            }
        }
        if (history.isNotEmpty()) {
            item { Text("Decryption history", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold) }
            items(history.take(30), key = { "history-${it.id}" }) { session ->
                OutlinedCard(Modifier.fillMaxWidth().clickable { onHistorySession(session.id) }) {
                    Column(Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(3.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(session.target.label, fontWeight = FontWeight.SemiBold, modifier = Modifier.weight(1f))
                            Text(DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT).format(Date(session.startedAt)), style = MaterialTheme.typography.labelSmall)
                        }
                        Text(session.target.packageName, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                        Text("${session.decryptedEvents} events · ${session.httpRequests} requests · ${session.tlsErrors} TLS errors", style = MaterialTheme.typography.bodySmall)
                    }
                }
            }
        }
        item { Spacer(Modifier.height(18.dp)) }
    }

    if (picker) AppPickerSheet(apps, selected, false, { if (it != null) selected = it; picker = false }, { picker = false })
    if (confirmReboot) AlertDialog(
        onDismissRequest = { confirmReboot = false },
        title = { Text("Reboot device?") },
        text = { Text("The Magisk CA overlay becomes active after reboot. The phone will disconnect from ADB briefly.") },
        confirmButton = { TextButton(onClick = { confirmReboot = false; viewModel.rebootDevice() }) { Text("Reboot") } },
        dismissButton = { TextButton(onClick = { confirmReboot = false }) { Text("Cancel") } },
    )
}

@Composable
private fun SetupRow(title: String, ready: Boolean, detail: String) {
    Row(verticalAlignment = Alignment.CenterVertically) {
        Icon(if (ready) Icons.Default.CheckCircle else Icons.Default.Error, null, tint = if (ready) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant)
        Spacer(Modifier.padding(5.dp))
        Column(Modifier.weight(1f)) { Text(title, fontWeight = FontWeight.Medium); Text(detail, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant) }
    }
}

@Composable
private fun SettingSwitch(title: String, detail: String, checked: Boolean, enabled: Boolean, onChecked: (Boolean) -> Unit) {
    Row(verticalAlignment = Alignment.CenterVertically) {
        Column(Modifier.weight(1f)) { Text(title, fontWeight = FontWeight.Medium); Text(detail, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant) }
        Switch(checked = checked, onCheckedChange = onChecked, enabled = enabled)
    }
}
